// api/_lib/demo-mode.js — Demo mode: auto-detect missing DEEPSEEK_API_KEY, return mock data
// Spec-002 (2026-06-14) — 方案 A: 自动检测 + 生产硬拒绝

/**
 * Returns true when DEEPSEEK_API_KEY is unset, empty, or "dummy".
 * In production (NODE_ENV=production), callers MUST check this and refuse demo mode.
 */
export function isDemoMode() {
  return !process.env.DEEPSEEK_API_KEY || process.env.DEEPSEEK_API_KEY === 'dummy';
}

/**
 * Generate a complete mock audit report.
 * Pure function — no external HTTP calls.
 */
export function generateDemoReport(url) {
  const domain = url.replace(/https?:\/\//, '').replace(/\/.*/, '');
  const timestamp = Date.now().toString(36);
  const random = Math.random().toString(36).substring(2, 8);

  return {
    reportId: `demo-${timestamp}-${random}`,
    summary: generateDemoSummary(domain),
    lighthouse: {
      performanceScore: 85,
      largestContentfulPaint: '2.8 s',
      cumulativeLayoutShift: '0.06',
      firstContentfulPaint: '1.6 s',
      totalBlockingTime: '180 ms',
    },
    htmlHead: {
      title: 'Demo Website | RoastAudit Mock',
      metaDescription: 'This is a demo audit report generated by RoastAudit. Upgrade to a real audit for your actual website.',
      ogTitle: 'Demo Website',
      ogDescription: 'A mock website for testing RoastAudit demo mode',
      ogImage: null,
      canonical: `https://${domain}`,
      h1: 'Welcome to Demo Website',
    },
  };
}

function generateDemoSummary(domain) {
  return `[DEMO MODE] This is a simulated audit report for ${domain}.
**Overall Score: 72/100** — Needs work.

### Performance (Lighthouse)
Lighthouse performance score is **85/100** (mobile). Largest Contentful Paint clocks in at 2.8 seconds — above the 2.5s recommended threshold. First Contentful Paint at 1.6s is acceptable. Cumulative Layout Shift (0.06) stays within Google's "good" range (< 0.1). Total Blocking Time of 180ms indicates moderate JavaScript overhead.

### Top 3 Critical Issues
1. **Missing meta description** — No meta description tag found, search engines will auto-generate snippets that may misrepresent content. Add a compelling 150-160 char description.
2. **Slow LCP** — Largest Contentful Paint exceeds 2.5s target, likely due to unoptimized images. Implement lazy loading and WebP format.
3. **Weak CTAs** — Call-to-action buttons lack contrast and urgency language, reducing conversion potential.

Unlock the full report for 15+ actionable fixes with code examples and a prioritized action plan.`;
}
