// GET /api/report-pdf?reportId=xxx — Generate PDF report

// Helper: Get data (KV or fallback to global)
async function getReport(reportId) {
  if (process.env.KV_URL) {
    try {
      const { kv } = await import('@vercel/kv');
      const data = await kv.get(`report:${reportId}`);
      return data ? (typeof data === 'string' ? data : JSON.stringify(data)) : null;
    } catch (err) {
      console.warn('KV get failed, falling back to memory:', err.message);
    }
  }

  // Fallback to process memory
  global.reports = global.reports || {};
  return global.reports[reportId] || null;
}

export default async function handler(req, res) {
  const reportId = req.query.reportId;

  if (!reportId) {
    return res.status(400).json({ error: 'Missing reportId' });
  }

  try {
    const reportData = await getReport(reportId);

    if (!reportData) {
      return res.status(404).json({ error: 'Report not found' });
    }

    const parsed = typeof reportData === 'string' ? JSON.parse(reportData) : reportData;

    if (!parsed.paid) {
      return res.status(403).json({ error: 'Report not paid' });
    }

    // For JSON format request (used by frontend to get full report)
    if (req.query.format === 'json') {
      return res.status(200).json({
        fullReport: parsed.fullReport,
        summary: parsed.summary,
        url: parsed.url,
      });
    }

    // Generate PDF
    const PDFDocument = (await import('pdfkit')).default;
    const doc = new PDFDocument({ margin: 50, size: 'A4' });

    // Set response headers
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="roastaudit-${reportId}.pdf"`);

    // Pipe PDF to response
    doc.pipe(res);

    // Cover page
    doc.fontSize(28).text('RoastAudit', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(16).text('Website Audit Report', { align: 'center' });
    doc.moveDown(2);

    // URL
    const domain = parsed.url.replace(/https?:\/\//, '').replace(/\/.*/, '');
    doc.fontSize(14).text(`Audited URL: ${domain}`, { align: 'center' });
    doc.fontSize(10).text(`Full URL: ${parsed.url}`, { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(10).text(`Date: ${new Date(parsed.createdAt).toLocaleDateString()}`, { align: 'center' });

    doc.moveDown(3);

    // Parse and render report content
    const reportText = parsed.fullReport;
    const lines = reportText.split('\n');

    for (const line of lines) {
      if (line.startsWith('# ')) {
        doc.moveDown(1);
        doc.fontSize(20).text(line.substring(2), { align: 'left' });
        doc.moveDown(0.5);
      } else if (line.startsWith('## ')) {
        doc.moveDown(0.8);
        doc.fontSize(16).text(line.substring(3), { align: 'left' });
        doc.moveDown(0.3);
      } else if (line.startsWith('### ')) {
        doc.moveDown(0.5);
        doc.fontSize(13).text(line.substring(4), { align: 'left' });
      } else if (line.startsWith('**') && line.endsWith('**')) {
        const boldText = line.substring(2, line.length - 2);
        doc.fontSize(10).text(boldText, { continued: false });
      } else if (line.startsWith('- ')) {
        doc.fontSize(10).text(`• ${line.substring(2)}`, { indent: 20 });
      } else if (line.startsWith('---')) {
        doc.moveDown(0.5);
        doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
        doc.moveDown(0.5);
      } else if (line.trim() === '') {
        doc.moveDown(0.3);
      } else {
        // Skip code blocks and other complex markdown for simplicity
        if (!line.startsWith('`') && !line.startsWith('```')) {
          doc.fontSize(10).text(line, { align: 'left' });
        }
      }
    }

    // Footer
    doc.moveDown(2);
    doc.fontSize(8).text('Generated by RoastAudit — roastaudit.com', { align: 'center' });

    // Finalize PDF
    doc.end();

  } catch (err) {
    console.error('PDF generation error:', err);
    if (!res.headersSent) {
      return res.status(500).json({ error: 'Failed to generate PDF' });
    }
  }
}
